// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant_Management_System.Data;

#nullable disable

namespace Restaurant_Management_System.Migrations
{
    [DbContext(typeof(rmsDbContext))]
    [Migration("20260721122322_Tables_Data_seeding")]
    partial class Tables_Data_seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant_Management_System.Models.BillInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("BillInvoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 5001,
                            OrderId = 1001,
                            PaymentStatus = 1,
                            SubtotalAmount = 1220.00m,
                            TaxAmount = 219.60m,
                            TipAmount = 50.00m,
                            TotalAmount = 1489.60m
                        },
                        new
                        {
                            InvoiceId = 5002,
                            OrderId = 1002,
                            PaymentStatus = 0,
                            SubtotalAmount = 500.00m,
                            TaxAmount = 90.00m,
                            TipAmount = 0.00m,
                            TotalAmount = 590.00m
                        },
                        new
                        {
                            InvoiceId = 5003,
                            OrderId = 1003,
                            PaymentStatus = 1,
                            SubtotalAmount = 240.00m,
                            TaxAmount = 43.20m,
                            TipAmount = 0.00m,
                            TotalAmount = 283.20m
                        },
                        new
                        {
                            InvoiceId = 5004,
                            OrderId = 1004,
                            PaymentStatus = 2,
                            SubtotalAmount = 350.00m,
                            TaxAmount = 63.00m,
                            TipAmount = 0.00m,
                            TotalAmount = 413.00m
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.CustomerOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("OrderId");

                    b.HasIndex("TableNumber");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            OrderId = 1001,
                            CustomerName = "Ravi",
                            OrderStatus = 3,
                            OrderTime = new DateTime(2026, 5, 21, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderType = 0,
                            TableNumber = "T07"
                        },
                        new
                        {
                            OrderId = 1002,
                            CustomerName = "Anita",
                            OrderStatus = 1,
                            OrderTime = new DateTime(2026, 5, 21, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            OrderType = 0,
                            TableNumber = "T08"
                        },
                        new
                        {
                            OrderId = 1003,
                            CustomerName = "Karan",
                            OrderStatus = 0,
                            OrderTime = new DateTime(2026, 5, 21, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            OrderType = 1,
                            TableNumber = "T03"
                        },
                        new
                        {
                            OrderId = 1004,
                            CustomerName = "Sita",
                            OrderStatus = 4,
                            OrderTime = new DateTime(2026, 5, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = 2,
                            TableNumber = "T02"
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpId = "AD01",
                            IsActive = true,
                            Name = "Shaik",
                            Role = "Admin",
                            password = "AD01@123"
                        },
                        new
                        {
                            Id = 2,
                            EmpId = "CH01",
                            IsActive = true,
                            Name = "Sai",
                            Role = "Chef",
                            password = "CH01@123"
                        },
                        new
                        {
                            Id = 3,
                            EmpId = "MN01",
                            IsActive = true,
                            Name = "Satya",
                            Role = "Manager",
                            password = "MN01@123"
                        },
                        new
                        {
                            Id = 4,
                            EmpId = "WA01",
                            IsActive = true,
                            Name = "Anusha",
                            Role = "Waiter",
                            password = "WA01@123"
                        },
                        new
                        {
                            Id = 5,
                            EmpId = "CS01",
                            IsActive = true,
                            Name = "Om Prakash",
                            Role = "Cashier",
                            password = "CS01@123"
                        },
                        new
                        {
                            Id = 6,
                            EmpId = "IC01",
                            IsActive = true,
                            Name = "Rishab",
                            Role = "Inventory Clerk",
                            password = "IC01@123"
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.HasIndex("IngredientName")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CurrentStock = 100.00m,
                            IngredientName = "Flour",
                            ReorderLevel = 20.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "KG"
                        },
                        new
                        {
                            IngredientId = 2,
                            CurrentStock = 50.00m,
                            IngredientName = "Chicken",
                            ReorderLevel = 10.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "KG"
                        },
                        new
                        {
                            IngredientId = 3,
                            CurrentStock = 40.00m,
                            IngredientName = "Cheese",
                            ReorderLevel = 10.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "KG"
                        },
                        new
                        {
                            IngredientId = 4,
                            CurrentStock = 60.00m,
                            IngredientName = "Potato",
                            ReorderLevel = 15.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "KG"
                        },
                        new
                        {
                            IngredientId = 5,
                            CurrentStock = 30.00m,
                            IngredientName = "Tomato",
                            ReorderLevel = 5.00m,
                            StockStatus = "LOW",
                            UnitOfMeasure = "KG"
                        },
                        new
                        {
                            IngredientId = 6,
                            CurrentStock = 500.00m,
                            IngredientName = "Garlic",
                            ReorderLevel = 100.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "G"
                        },
                        new
                        {
                            IngredientId = 7,
                            CurrentStock = 10.00m,
                            IngredientName = "Oil",
                            ReorderLevel = 2.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "L"
                        },
                        new
                        {
                            IngredientId = 8,
                            CurrentStock = 20.00m,
                            IngredientName = "Sugar",
                            ReorderLevel = 5.00m,
                            StockStatus = "AVAILABLE",
                            UnitOfMeasure = "KG"
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.ItemRecipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("RecipeId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("ItemRecipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            MenuItemId = 1,
                            Quantity = 0.30m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 2,
                            MenuItemId = 1,
                            Quantity = 0.20m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 3,
                            MenuItemId = 1,
                            Quantity = 0.15m
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 1,
                            MenuItemId = 2,
                            Quantity = 0.28m
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 3,
                            MenuItemId = 2,
                            Quantity = 0.12m
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 4,
                            MenuItemId = 4,
                            Quantity = 0.25m
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 8,
                            MenuItemId = 5,
                            Quantity = 0.33m
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 6,
                            MenuItemId = 6,
                            Quantity = 0.02m
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.KitchenTicket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("AssignedChef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("OrderId");

                    b.ToTable("KitchenTickets");

                    b.HasData(
                        new
                        {
                            TicketId = 3001,
                            AssignedChef = "Sai",
                            OrderId = 1002,
                            StartTime = new DateTime(2026, 5, 21, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            Station = "Pizza Oven",
                            TicketStatus = 1
                        },
                        new
                        {
                            TicketId = 3002,
                            AssignedChef = "Rishab",
                            CompletionTime = new DateTime(2026, 5, 21, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1001,
                            StartTime = new DateTime(2026, 5, 21, 12, 35, 0, 0, DateTimeKind.Unspecified),
                            Station = "Grill",
                            TicketStatus = 3
                        },
                        new
                        {
                            TicketId = 3003,
                            OrderId = 1003,
                            Station = "Fryer",
                            TicketStatus = 0
                        },
                        new
                        {
                            TicketId = 3004,
                            OrderId = 1004,
                            Station = "Oven",
                            TicketStatus = 2
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RecipeSteps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Category = "Pizza",
                            ItemName = "BBQ Chicken Pizza",
                            ItemStatus = 0,
                            PreparationTime = 20,
                            Price = 550.00m
                        },
                        new
                        {
                            MenuItemId = 2,
                            Category = "Pizza",
                            ItemName = "Farm House Pizza",
                            ItemStatus = 0,
                            PreparationTime = 18,
                            Price = 500.00m
                        },
                        new
                        {
                            MenuItemId = 3,
                            Category = "Pizza",
                            ItemName = "Margherita",
                            ItemStatus = 0,
                            PreparationTime = 15,
                            Price = 350.00m
                        },
                        new
                        {
                            MenuItemId = 4,
                            Category = "Sides",
                            ItemName = "Fries",
                            ItemStatus = 0,
                            PreparationTime = 8,
                            Price = 120.00m
                        },
                        new
                        {
                            MenuItemId = 5,
                            Category = "Beverage",
                            ItemName = "Coke",
                            ItemStatus = 0,
                            PreparationTime = 1,
                            Price = 50.00m
                        },
                        new
                        {
                            MenuItemId = 6,
                            Category = "Sides",
                            ItemName = "Garlic Bread",
                            ItemStatus = 0,
                            PreparationTime = 7,
                            Price = 90.00m
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 2001,
                            MenuItemId = 1,
                            OrderId = 1001,
                            Price = 550.00m,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = 2002,
                            MenuItemId = 4,
                            OrderId = 1001,
                            Price = 120.00m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 2003,
                            MenuItemId = 2,
                            OrderId = 1002,
                            Price = 500.00m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 2004,
                            MenuItemId = 4,
                            OrderId = 1003,
                            Price = 120.00m,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = 2005,
                            MenuItemId = 3,
                            OrderId = 1004,
                            Price = 350.00m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.RestaurantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseCgstPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSgstPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RestaurantProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseCgstPercentage = 9.00m,
                            BaseSgstPercentage = 9.00m,
                            CorporateEmail = "operations@pizzahub.com",
                            PhysicalAddress = "1024, Banjara Hills, Hyderabad, Telangana",
                            PrimaryPhone = "+91 987654321",
                            RestaurantName = "Pizza Hub",
                            TaxIdentifier = "GSTIN9283471029B1Z4"
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.RestaurantTable", b =>
                {
                    b.Property<string>("TableNumber")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.HasKey("TableNumber");

                    b.ToTable("RestaurantTables");

                    b.HasData(
                        new
                        {
                            TableNumber = "T01",
                            IsOccupied = false
                        },
                        new
                        {
                            TableNumber = "T02",
                            IsOccupied = false
                        },
                        new
                        {
                            TableNumber = "T03",
                            IsOccupied = false
                        },
                        new
                        {
                            TableNumber = "T04",
                            IsOccupied = false
                        },
                        new
                        {
                            TableNumber = "T05",
                            IsOccupied = false
                        },
                        new
                        {
                            TableNumber = "T06",
                            IsOccupied = false
                        },
                        new
                        {
                            TableNumber = "T07",
                            IsOccupied = true
                        },
                        new
                        {
                            TableNumber = "T08",
                            IsOccupied = true
                        },
                        new
                        {
                            TableNumber = "T09",
                            IsOccupied = true
                        },
                        new
                        {
                            TableNumber = "T10",
                            IsOccupied = true
                        });
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.BillInvoice", b =>
                {
                    b.HasOne("Restaurant_Management_System.Models.CustomerOrder", "CustomerOrder")
                        .WithOne("BillInvoice")
                        .HasForeignKey("Restaurant_Management_System.Models.BillInvoice", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.CustomerOrder", b =>
                {
                    b.HasOne("Restaurant_Management_System.Models.RestaurantTable", "TableStatus")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("TableNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableStatus");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.ItemRecipe", b =>
                {
                    b.HasOne("Restaurant_Management_System.Models.Ingredient", "Ingredient")
                        .WithMany("ItemRecipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Management_System.Models.MenuItem", "MenuItem")
                        .WithMany("ItemRecipes")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.KitchenTicket", b =>
                {
                    b.HasOne("Restaurant_Management_System.Models.CustomerOrder", "CustomerOrder")
                        .WithMany("KitchenTickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.OrderItem", b =>
                {
                    b.HasOne("Restaurant_Management_System.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_Management_System.Models.CustomerOrder", "CustomerOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.CustomerOrder", b =>
                {
                    b.Navigation("BillInvoice");

                    b.Navigation("KitchenTickets");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.Ingredient", b =>
                {
                    b.Navigation("ItemRecipes");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.MenuItem", b =>
                {
                    b.Navigation("ItemRecipes");
                });

            modelBuilder.Entity("Restaurant_Management_System.Models.RestaurantTable", b =>
                {
                    b.Navigation("CustomerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
