// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant_Management_System.Data;

#nullable disable

namespace Restaurant_Management_System.Migrations
{
    [DbContext(typeof(rmsDbContext))]
    [Migration("20260708162904_rename_user_Employee")]
    partial class rename_user_Employee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant_Management_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpId = "AD01",
                            Name = "Shaik",
                            Role = "Admin",
                            password = "AD01@123"
                        },
                        new
                        {
                            Id = 2,
                            EmpId = "CH01",
                            Name = "Sai",
                            Role = "Chef",
                            password = "CH01@123"
                        },
                        new
                        {
                            Id = 3,
                            EmpId = "MN01",
                            Name = "Satya",
                            Role = "Manager",
                            password = "MN01@123"
                        },
                        new
                        {
                            Id = 4,
                            EmpId = "WA01",
                            Name = "Anusha",
                            Role = "Waiter",
                            password = "WA01@123"
                        },
                        new
                        {
                            Id = 5,
                            EmpId = "CS01",
                            Name = "Om Prakash",
                            Role = "Cashier",
                            password = "CS01@123"
                        },
                        new
                        {
                            Id = 6,
                            EmpId = "IC01",
                            Name = "Rishab",
                            Role = "Inventory Clerk",
                            password = "IC01@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
